export const locationCards = [
  {
    idx: 1,
    pos: 1,
    active: true,
    image: '/locations/butuan.svg',
    title: 'ARISE BUTUAN',
    date: 'May 26, 2024',
  },
  {
    idx: 2,
    pos: 2,
    active: true,
    image: '/locations/davao.svg',
    title: 'ARISE DAVAO',
    date: 'June 1, 2024',
  },
  {
    idx: 3,
    pos: 3,
    active: true,
    image: '/locations/hongkong.svg',
    title: 'ARISE HONG KONG',
    date: 'July 20-21, 2024',
  },
  {
    idx: 4,
    pos: 4,
    active: true,
    image: '/locations/indonesia.svg',
    title: 'ARISE INDONESIA',
    date: 'July 31-Aug 3, 2024',
  },
  {
    idx: 5,
    pos: 5,
    active: true,
    image: '/locations/bicol.svg',
    title: 'ARISE BICOL',
    date: 'August 13-15, 2024',
  },
  {
    idx: 6,
    pos: 6,
    active: true,
    image: '/locations/myanmar.svg',
    title: 'ARISE MYANMAR',
    date: 'October 15-17, 2024',
  },
  {
    idx: 7,
    pos: 7,
    active: true,
    image: '/locations/nepal.svg',
    title: 'ARISE NEPAL',
    date: 'October 20-23, 2024',
  },
  {
    idx: 8,
    pos: 8,
    active: true,
    image: '/locations/mongolia.svg',
    title: 'ARISE MONGOLIA',
    date: 'October 2024',
  },
  {
    idx: 9,
    pos: 9,
    active: true,
    image: '/locations/latino.svg',
    title: 'ARISE LATINO',
    date: 'November 11-14, 2024',
  },
  {
    idx: 10,
    pos: 10,
    active: true,
    image: '/locations/bangladesh.svg',
    title: 'ARISE BANGLADESH',
    date: 'March 2025',
  },
  {
    idx: 11,
    pos: 11,
    active: true,
    image: '/locations/japan.svg',
    title: 'ARISE JAPAN',
    date: 'March 2025',
  },
  {
    idx: 12,
    pos: 12,
    active: true,
    image: '/locations/macau.svg',
    title: 'ARISE MACAU',
    date: 'August 2025',
  },
  {
    idx: 13,
    pos: 13,
    active: true,
    image: '/locations/philippines.svg',
    title: 'ARISE PHILIPPINES',
    date: '2025',
  },
  {
    idx: 14,
    pos: 14,
    active: true,
    image: '/locations/singapore.svg',
    title: 'ARISE SINGAPORE',
    date: 'March 2025',
  },
  {
    idx: 15,
    pos: 15,
    active: true,
    image: '/locations/vietnam.svg',
    title: 'ARISE VIETNAM',
    date: 'TBD',
  },
  {
    idx: 16,
    pos: 16,
    active: true,
    image: '/locations/india.svg',
    title: 'ARISE INDIA',
    date: 'TBD',
  },
  {
    idx: 17,
    pos: 17,
    active: true,
    image: '/locations/srilanka.svg',
    title: 'ARISE SRI LANKA',
    date: 'TBD',
  },
  {
    idx: 18,
    pos: 18,
    active: true,
    image: '/locations/cambodia.svg',
    title: 'ARISE CAMBODIA',
    date: 'TBD',
  },
];
