export const momentsCards = [
  {
    idx: 1,
    pos: 1,
    image: '/images/DAY1_IBIS-Fellowship-Night.jpg',
    title: 'Day 1',
    description: 'IBIS Fellowship Night',
    active: true,
  },
  {
    idx: 2,
    pos: 2,
    image: '/images/DAY1_PANEL.jpg',
    title: 'Day 1',
    description: 'Justice Issues Panel',
    active: true,
  },
  {
    idx: 3,
    pos: 3,
    image: '/images/DAY1_WORSHIP.jpg',
    title: 'Day 1',
    description: 'Night Session Worship',
    active: true,
  },
  {
    idx: 4,
    pos: 4,
    image: '/images/DAY2_Exhibition.jpg',
    title: 'Day 2',
    description: 'Missional Partners and Organizations Exhibitors',
    active: true,
  },
  {
    idx: 5,
    pos: 5,
    image: '/images/DAY2_INNOVATION_LAB.jpg',
    title: 'Day 2',
    description: 'Innovation Lab',
    active: true,
  },
  {
    idx: 6,
    pos: 6,
    image: '/images/DAY2_Performance-from-Mongolian-Dancers.jpg',
    title: 'Day 2',
    description: 'Performance from Mongolian Dance',
    active: true,
  },
  {
    idx: 7,
    pos: 7,
    image: '/images/DAY2_Workshops.jpg',
    title: 'Day 2',
    description: 'Workshops',
    active: true,
  },
  {
    idx: 8,
    pos: 8,
    image: '/images/DAY3_Group-Picture-Morning-Session.jpg',
    title: 'Day 3',
    description: 'Morning Session Congregation',
    active: true,
  },
  {
    idx: 9,
    pos: 9,
    image: '/images/DAY3_HISPOP.jpg',
    title: 'Day 3',
    description: 'HISPOP Worship Session',
    active: true,
  },
  {
    idx: 10,
    pos: 10,
    image: '/images/DAY4_Response-Time_Praying.jpg',
    title: 'Day 4',
    description: 'Praying at Response Time',
    active: true,
  },
  {
    idx: 11,
    pos: 11,
    image: '/images/DAY5_Pray-Closing.jpg',
    title: 'Day 5',
    description: 'Closing Session Prayer',
    active: true,
  },
];

export const momentThumbnails = momentsCards.map((card) => ({
  id: card.idx,
  image: card.image,
  title: card.title,
}));
